### ISSUE TITLE
Wormhole from one component to another

### ISSUE THREAD

**Issue by adambedford** [yapplabs/ember-wormhole#103]
Is it possible to wormhole from one component to another? I'm getting the "missing DOM element" error in the console and the wormholed content is rendering in place

**Comment by lukemelia** [comment]
The component with the destination DOM would need to be rendered at the time the source component is attempting to wormhole into it. It sounds like perhaps it isn't in your case. You may find that [ember-elsewhere](https://github.com/ef4/ember-elsewhere) is a better fit for sending a component reference from one spot to another component.

**Comment by adambedford** [comment]
Thanks @lukemelia for the suggestion to use ember-elsewhere, it is working out perfectly!
