### ISSUE TITLE
Ember 3

### ISSUE THREAD

**Issue by txm** [yapplabs/ember-wormhole#108]
Any plans to support Ember v3?

**Comment by lukemelia** [comment]
Hi @txm, we are using wormhole with Ember 3. Are you experiencing difficulties?

**Comment by txm** [comment]
I saw a warning on the cli from `ember s`
`DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: ember-commons -> ember-wormhole -> ember-cli-babel`

In any event it turns out the unit test that was failing was due to an upgrade from `0.3.6` to `0.4.0`.  I'm not sure it's down to being subclassed, but either way, unrelated to ember 3 so I'll close this issue.  I appreciate the response.
