### ISSUE TITLE
How future proof is this library?

### ISSUE THREAD

**Issue by ssured** [yapplabs/ember-wormhole#13]
First of all, thanks for this lib!

Even while it does not use private API, I wonder how future proof this is. It works great for me with Ember Glimmer 1.13. But what will happen when more advanced techniques are introduced to Glimmer? Shadow dom will get broken if we move Dom objects around, right? Maybe you can shed some light on the future stability of this plugin, it will help me deciding to highly use it in my UI.

Thanks

**Comment by lukemelia** [comment]
Hi @ssured. Ember core team member @krisselden was involved in helping us use public API to implement this addon. In addition, I know of at least one other core team member using this addon in client work. While you're correct that there are general tradeoffs to this addon's technique, Ember's API is not expected to be one of those tradeoffs.

**Comment by ssured** [comment]
Thanks for your quick reply. I feel comfortable using the plugin, knowing it is core supported. Maybe something along your lines can be put in the readme, so others will know too.
