### ISSUE TITLE
"wormholing" elements destroys focus, selection

### ISSUE THREAD

**Issue by adamesque** [yapplabs/ember-wormhole#22]
If an element to be sent through an ember-wormhole currently has (or is the parent of an element that has) focus, the process of reparenting the element during `appendRange` destroys focus and shifts `document.activeElement` back to the `<body>`.

I'm running into this when using [ember-cli-focus-input](https://github.com/williamsbdev/ember-cli-focus-input) inside an [ember-modal-dialog](https://github.com/yapplabs/ember-modal-dialog) — the `{{focus-input}}` component's `didInsertElement` handler fires first, focuses & selects the input element, but if the dialog is also opening at the same time, the wormhole's `didInsertElement` fires last, reparenting the DOM nodes and wiping out the focus.

It might be reasonable to check `document.activeElement` at the beginning of `appendToDestination` and hang on the element if it's part of the wormhole's content so focus could be restored on the other side of `appendRange`.

I'm not sure how much extra work you'd need to do to preserve selection ranges as well; I mostly care about the selection inside the text input, which might be easier to handle than generic selection.

**Comment by krisselden** [comment]
can you add a test for this?

**Comment by adamesque** [comment]
Oh weird — I did! It's in the [PR](#23), right?

**Comment by krisselden** [comment]
Sorry, I assumed it was squashed, it is the PR, I was just looking at the one commit by mistake.

**Comment by adamesque** [comment]
No worries — I can squash too if that's what you prefer. Thanks for taking a look!
