### ISSUE TITLE
Destination rerender breaks subsequent data changes

### ISSUE THREAD

**Issue by knownasilya** [yapplabs/ember-wormhole#3]
I have something like the following, where the content of `setContent` is the destination. I recreate this destination every time, without changing the `to` attribute. Since the `destinationElement` is cached, the wormhole only works the first time, but once the popup is re-rendered it does not put the new data there.

```js
      openPopup(lane) {
        var popup = this.get('mapPopup');
        var feature = lane.get('boothFeature');
        var map = this.get('map');

        if (popup.getPosition()) {
          this.set('lane', undefined);
          popup.close();
        }

        if (feature) {
          let latlng = feature.getGeometry().get();
          let id = lane.get('id');
          let wormhole = this.get('wormhole');

          popup.setContent(`<div id='infowindow'></div>`);
          popup.setPosition(latlng);
          popup.open(map);
          this.set('lane', lane);

          // see routable-site template for wormhole/infowindow layout
          if (wormhole) {
            wormhole.rerender();
          }
        }
      },
```

```hbs
{{#if lane}}
  {{#ember-wormhole to='infowindow' viewName='wormhole'}}
    Lane #: <b>{{lane.number}}</b><br>
    Mode: <b>{{lane.mode}}</b><br>
    Avg. Wait Time: <b>na</b>
  {{/ember-wormhole}}
{{/if}}
```

**Comment by lukemelia** [comment]
@knownasilya not sure I'm totally following this. Is it addressed by the public API branch being merged?

**Comment by knownasilya** [comment]
I don't think so, since the element is still cached. https://github.com/yapplabs/ember-wormhole/blob/master/addon/components/ember-wormhole.js#L11

**Comment by lukemelia** [comment]
When `destinationElementId` changes, `destinationElement` will be invalidated, which triggers https://github.com/yapplabs/ember-wormhole/blob/master/addon/components/ember-wormhole.js#L28, which moves the DOM nodes to the new destinationElement. If I'm missing something, maybe you could create a failing test to demonstrate?

**Comment by knownasilya** [comment]
Ah, missed that. Yes this should be solved. I'll give it a go to confirm.

**Comment by knownasilya** [comment]
@lukemelia `destinationDidChange` never triggers, and the element is there. How does that observer work, if the element is the same as before?

**Comment by knownasilya** [comment]
@lukemelia Also, if the `to` doesn't change, how will the `destinationElement` change, since it's cached and if removed from the DOM, does that reflect on the object?

Seems like the flow is `to` changed, get the element, element changed, append.
There isn't a path anywhere that says if element removed, recompute it, no matter if `to` changed or not.

**Comment by lukemelia** [comment]
I think I need a test to understand. We're not observing the DOM -- that's against Ember's philosophy after all...

**Comment by krisselden** [comment]
The target being inside a view with a shorter lifespan is not supported.

**Comment by krisselden** [comment]
To clarify further, you shouldn't target unstable dom elements, the element needs to stay stable while the wormhole component is rendered, generally people target an element sibling to the app, if you target within the app, you need to be careful the dom you target belongs to a view that will outlive the view the wormhole is in, also, that you are targeting a static element (not managed by ember).
