### ISSUE TITLE
Inner component action sent to wormhole component instead of outer component (canary)

### ISSUE THREAD

**Issue by mdehoog** [yapplabs/ember-wormhole#33]
Using Ember canary, when an "outer" component has an "inner" component that's inside a wormhole, and the "inner" component sends an action, the action is fired on the wormhole itself, causing the error:
```
Uncaught Error: <emberapp@component:ember-wormhole::ember609> had no action handler for: actionName
```
It used to be fired correctly on the "outer" component, but is broken since https://github.com/emberjs/ember.js/pull/12289.

I've also raised an issue on the ember.js repository: https://github.com/emberjs/ember.js/issues/12317, but thought the issue may be able to fixed on the ember-wormhole side, or you might have some insight into how to fix the regression.

Note that this is only an error if the "inner" component and wormhole are defined in an "outer" component template; the action works fine if the component/wormhole are in a controller template.

This fiddle reproduces the issue: http://ember-twiddle.com/1c59a1dcdb18eec69a8e. Changing the ember dependency from `canary` to `release` in `twiddle.json` fixes the issue.

**Comment by mdehoog** [comment]
Seems to be fixed, see comment in emberjs/ember.js#12317.

**Comment by lukemelia** [comment]
👍  Thanks for following up, @mdehoog
