### ISSUE TITLE
[Idea] component for the wormhole output 

### ISSUE THREAD

**Issue by knownasilya** [yapplabs/ember-wormhole#39]
Basically the wormhole would know when the receiver is rendered, and only then would it transfer the yielded content.

Something like the following:

```hbs
<!-- application/template.hbs -->
{{#if menuOpen}}
  {{#ember-wormhole-receiver 'sidebar-menu'}}
    Default application wide menus here
  {{/ember-wormhole-receiver}}
{{/if}}
```

```hbs
<!-- some/route/template.hbs -->
{{#ember-wormhole 'sidebar-menu'}}
  Route menu items here with their own actions and context
{{/ember-wormhole}}
```

This would allow for easier implementations (not when trying to integrate with third-party libs) when working in an ember app. Think a sidebar that has a header (defined in `application/template.hbs`) with a dropdown menu. The sidebar content could be in any route, so we have a receiver in the header and any route can now manipulate that menu easily without having to wire up a service with a boolean.

Underneath, the two components would communicate via a service based on the identifier shared by the two.

**Comment by knownasilya** [comment]
You could do things like:

```hbs
<div class="profile-header">
  {{#ember-wormhole-receiver 'header'}}
  {{else}}
    Alternate content when not rendered
  {{/ember-wormhole-receiver}}
</div>

<div class="profile-body">
  {{yield (hash
    header=(component 'ember-wormhole' 'header')
    footer=(component 'ember-wormhole' 'footer')
  )}}
</div>

<div class="profile-footer">
  {{#ember-wormhole-receiver 'footer'}}
  {{else}}
    Default footer
  {{/ember-wormhole-receiver}}
</div>
```

which could be used like:

```hbs
{{#user-profile as |areas|}}
  {{#areas.header}}
    Custom Header
  {{/areas.header}}

  {{#areas.footer}}
    Custom Footer
  {{/areas.footer}}
{{/user-profile}}
```

**Comment by knownasilya** [comment]
This might be better as another addon..

**Comment by lukemelia** [comment]
@knownasilya sounds a lot like https://github.com/minutebase/ember-portal which is built on top of wormhole.

**Comment by knownasilya** [comment]
Nice, didn't know about that.

**Comment by knownasilya** [comment]
For anyone interested, here's a working example with ember-portal, https://github.com/knownasilya/ember-yielded-portals#yielded-portals

**Comment by knownasilya** [comment]
Here's another interesting implementation I came up with: https://github.com/knownasilya/ember-receive
