### ISSUE TITLE
Packaged versions of ember wormhole lose focus on "wormholing"

### ISSUE THREAD

**Issue by foopoiuyt** [yapplabs/ember-wormhole#41]
Hello, we were running into the same issue as fixed in #23. It appears that the last packaged version (0.3.4) was released before that was merged, so it still happens when just doing an "ember install ember-wormhole". Would it be possible to get a newer version released?

Thanks.

**Comment by chrislopresto** [comment]
Sure thing

**Comment by chrislopresto** [comment]
v0.3.5 is up now. Sorry about that!

**Comment by foopoiuyt** [comment]
Thanks.
