### ISSUE TITLE
Is there a callback (action) when the rendering has been done

### ISSUE THREAD

**Issue by ayoubgdah** [yapplabs/ember-wormhole#42]
How to hook an action once the component has done the job of moving the DOM element?

**Comment by lukemelia** [comment]
@ayoubgdah the DOM relocation happens synchronously during `didInsertElement`, which is during the Ember run loop's `render` queue, so if you schedule something on the `afterRender` queue (e.g. `Ember.run.schedule('afterRender', this, this.doMyUsefulThing);`), you should be good. Feel free to reopen if that doesn't solve your use case.
