### ISSUE TITLE
[Feature] Destination component which fires up an action when wormhole is mounted

### ISSUE THREAD

**Issue by pavloo** [yapplabs/ember-wormhole#44]
I have a use case, when I need to have some way of notifying context when wormhole is mounted into destination, eg
```handlebars
{{destination elementId="destination_id" action="wormholeMounted"}}
```
```handlebars
{{#ember-wormhole to="destination_id"}}
Content
{{/ember-wormhole}}
```
So when wormhole's content is inserted into `{{destination`, action `wormholeMounted` is fired. I already implemented this using [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) in my app. Do you think it might be useful having this feature as a part of this addon? If yes, I will issue a PR. Thanks.

**Comment by chrislopresto** [comment]
Generally speaking we seek to avoid inferring application state from DOM. Could you provide more details? I'm curious as to why you couldn't extend from `ember-wormhole` and add additional logic in  `didInsertElement`. 

I imagine something along these lines would work:

```javascript
import EmberWormhole from 'ember-wormhole/components/ember-wormhole';

export default EmberWormhole.extend({
  didInsertElement() {
    this._super(...arguments);
    // Send your context notification here
  }
});
```

**Comment by pavloo** [comment]
@chrislopresto yeah, it will work out. I over-engineered this thing. The issue can be closed. Thanks.

**Comment by chrislopresto** [comment]
:+1:
