### ISSUE TITLE
Render a child view after target instead of inside it

### ISSUE THREAD

**Issue by djsegal** [yapplabs/ember-wormhole#45]
Is this currently possible? I want to ember-wormhole some `<li>` blocks into a `<ul>`.

Right now I can't get it to work because it is putting the `<li>` blocks into a div and breaking some css.

**Comment by lukemelia** [comment]
@djsegal This is not currently possible.

**Comment by djsegal** [comment]
@lukemelia we can close this, I found a way around it.

-----------

In my case, I was building a sidebar with breadcrumbs at the top and an index list at the bottom. Because of the temporality of the problem, I was able to just add everything sequentially (i.e. add one bread crumb for each depth of a resource and then a link for all its children). 

Because I resolved this issue, I can't think of a use case that would require rendering child views after targets

**Comment by lukemelia** [comment]
Thanks for the followup @djsegal
