### ISSUE TITLE
Ability to replace content instead of appending

### ISSUE THREAD

**Issue by trentmwillis** [yapplabs/ember-wormhole#48]
Looking at [the current code](https://github.com/yapplabs/ember-wormhole/blob/0dfc76e82967a6876edfdbbd74f4cc7d5b928344/addon/components/ember-wormhole.js#L19), it seems that `ember-wormhole` only supports appending content into the destination. While this makes sense in a lot of cases, we have a use-case where it would be beneficial to replace the content of the destination instead.

In short, we have a portion of our app being SSR'd and after boot up on the client, we're using `ember-wormhole` to inject some dynamic content and it works wonderfully. But, for SEO and slower phones, we initially render some placeholder content, which we currently have to manually remove. It would be nice if `ember-wormhole` could handle that for us.

Edit: if this seems like a reasonable ask, I'll implement it.

**Comment by lukemelia** [comment]
Closing in favor of discussion on #52
