### ISSUE TITLE
[Glimmer] Doesn't work in canary since glimmer was enabled

### ISSUE THREAD

**Issue by cibernox** [yapplabs/ember-wormhole#64]
The error is in this line: https://github.com/yapplabs/ember-wormhole/blob/18182d598f9ef015a87c112d7d5e50ca19fb3c6f/addon/components/ember-wormhole.js#L39

`this.renderer._dom` is not longer available.

**Comment by lukemelia** [comment]
@bantic WDYT?

**Comment by bantic** [comment]
I think that renderer, or at least the `dom` should definitely still be available in glimmer, although it must be exposed in a different way. I will take a look.

**Comment by cibernox** [comment]
Can 0.4.1 (or a beta) containing this be published?

**Comment by lukemelia** [comment]
@cibernox done https://github.com/yapplabs/ember-wormhole/releases/tag/0.4.1
