### ISSUE TITLE
this._dom is undefined for Glimmer2 + Fastboot

### ISSUE THREAD

**Issue by simonihmig** [yapplabs/ember-wormhole#69]
When running addon tests in a Fastboot environment, I get the following exception since canary includes Glimmer2:

> TypeError: Cannot read property 'document' of undefined

I tracked this down, this comes from this line of code: https://github.com/yapplabs/ember-wormhole/blob/master/addon/components/ember-wormhole.js#L41. 

Further debugging showed that `renderer._env.getDOM()` indeed returns `undefined` over here: https://github.com/yapplabs/ember-wormhole/blob/master/addon/utils/dom.js#L50

Again, this is for the combo Glimmer2 + Fastboot. I had no problems with 2.8 in Fastboot, or beta/canary in the browser!

**Comment by lukemelia** [comment]
@simonihmig are you testing with the latest release? (0.4.1) Not all Glimmer2 issues are addressed, but I believe this one has been.

**Comment by simonihmig** [comment]
Yes, I am! Should have mentioned that...

**Comment by nmcclay** [comment]
I also encountered this today testing with ember-cli@2.9.0-beta.1 which has Glimmer 2 enabled by default (I'm not certain about fastboot). My partials that rely on wormhole are crashing on the same line 41 that @simonihmig indicated.

**Comment by nmcclay** [comment]
Hmm... apparently I'm mistaken.  Pulling the latest version of ember-wormhole this issue has gone away for me.  Apologies for the false positive!

**Comment by lukemelia** [comment]
I believe this has been addressed as of 0.5.0.
