### ISSUE TITLE
Source Code for Demo?

### ISSUE THREAD

**Issue by graham-sportsmgmt** [yapplabs/ember-wormhole#78]
Excellent demo, where can we find the source code for it?

**Comment by lukemelia** [comment]
It can be found in this addon's dummy app: https://github.com/yapplabs/ember-wormhole/tree/master/tests/dummy

**Comment by graham-sportsmgmt** [comment]
Should that link not be included right underneath the link to the demo itself?

**Comment by lukemelia** [comment]
Great idea @graham-sportsmgmt! Want to open a PR?

**Comment by graham-sportsmgmt** [comment]
I'm new to this GitHub thing.  I'll try to figure out what you just said and do it though :)

**Comment by lukemelia** [comment]
@graham-sportsmgmt Great, thanks. This is the perfect kind of thing for your first PR!

**Comment by graham-sportsmgmt** [comment]
Which branch should I use for this?  Is it possible to have a documentation branch created?

**Comment by lukemelia** [comment]
@graham-sportsmgmt you can create a branch off of master in order to use for the PR. An example name could be "doc-add-link-to-readme"

**Comment by graham-sportsmgmt** [comment]
GitHub wasn't letting me create a branch, but it created one automatically as I saved the edits to readme.md.  PR generated, thanks for your guidance on this!
