### ISSUE TITLE
Programatically changing template?

### ISSUE THREAD

**Issue by graham-sportsmgmt** [yapplabs/ember-wormhole#81]
My use case will require us to change the content in a section depending on an input action elsewhere on the page.  Let's say that my navbar has two buttons on it, A and B.  When the user clicks A we need to load template X into the wormhole and when they click B we need to load template Y into the wormhole.

Is this possible?

I see how the demo/dummy app is linking a wormhole to a variable called "sidebar" and switching the value in that sidebar to determine where the content is rendered.  Would this mean that I'd create a bunch of wormholes each with the content I want to render and then use variables linked to their "to=" properties?

**Comment by lukemelia** [comment]
@graham-sportsmgmt There are a few ways to approach this, but a simple one might be:

```hbs
<nav>
  <button {{action "showX"}}>Button A</button>
  <button {{action "showY"}}>Button B</button>
</nav>

{{#ember-wormhole to="wormholeDestinaton"}}
  {{#if isShowingX}}
    {{x-component}}
  {{/if}}
  {{#if isShowingY}}
    {{y-component}}
  {{/if}}
{{/ember-wormhole}}
```

```js
  export default Ember.Controller.extend({
    isShowingX: false,
    isShowingY: false,
    actions: {
      showX() {
        this.setProperties({
          isShowingX: true,
          isShowingY: false
        });
      },
      showY() {
        this.setProperties({
          isShowingX: false,
          isShowingY: true
        });
      }
    }
  });
```

**Comment by lukemelia** [comment]
I hope that gave you the direction you needed. Feel free to reopen if necessary.
