### ISSUE TITLE
Triggers error on Glimmer

### ISSUE THREAD

**Issue by dschmidt** [yapplabs/ember-wormhole#9]
Hey,

after I upgraded from 0.1.x to latest release I can successfully open a wormhole. 
When I try to navigate to another page tho, I get this error:

```
TypeError: Cannot read property 'previousSibling' of null
    at removeRange (ember-wormhole.js:62)
    at ember-wormhole.js:29
    at Queue.invokeWithOnError (ember.debug.js:887)
    at Object.Queue.flush (ember.debug.js:943)
    at Object.DeferredActionQueues.flush (ember.debug.js:748)
    at Object.Backburner.end (ember.debug.js:173)
    at Object.Backburner.run (ember.debug.js:219)
    at Object.run (ember.debug.js:17119)
    at ember$data$lib$system$adapter$$Adapter.extend.ajax.Ember.RSVP.Promise.hash.success (rest-adapter.js:788)
```

Really not sure if this is a Glimmer regression or wormhole using private deprecated API, so opening an issue here for starters.

BR,
Dominik

**Comment by lukemelia** [comment]
Thanks for the report @dschmidt. Our tests are failing on canary with the same error. @krisselden and I spent some time investigating last night and were able to reproduce this error on canary without wormhole: http://emberjs.jsbin.com/mileqicono/3/edit

**Comment by krisselden** [comment]
@dschmidt it would be helpful to have reproduction steps that don't involve App.reset(), there is some race condition in view.destroy() in the glimmer branch I'd like to get to the bottom of.

**Comment by dschmidt** [comment]
@krisselden I'm pretty sure we don't use that in our application, still I'm not sure how to reproduce this in a minimal scope. I can try to isolate it tomorrow, otherwise - if I can't -, I can offer you to get access to the project to fiddle around with it yourself, I just can't disclose the repository publicly.

**Comment by krisselden** [comment]
@dschmidt I've further narrowed it down to the {{#if }} helper destroys the component on falsy but leaves the destroyed component in the childViews of the parent, which leads to the eventual calling of willDestroyElement after it has already been destroyed, this is for certain a bug in canary and not in this library.

**Comment by dschmidt** [comment]
Alright, thanks!

**Comment by krisselden** [comment]
@dschmidt here is a jsbin of the glimmer issue http://output.jsbin.com/didaqevibi/1and here is the issue in ember tracking it https://github.com/emberjs/ember.js/issues/11077
